language: java
dist: trusty
jdk: oraclejdk11
git:
  depth: false
addons:
  sonarcloud:
    organization: "kuul-development"
install: skip
script:
    - mvn clean install -Pcoverage
    - sonar-scanner